---
- name: Fetch latest AdGuardHome release from GitHub.
  ansible.builtin.uri:
    url: https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest
    return_content: true
  register: __adguardhome_latest_release
  when: adguardhome_version | length == 0

- name: Set AdGuardHome version fact.
  ansible.builtin.set_fact:
    __adguardhome_version: >-
      {{
        adguardhome_version if adguardhome_version | length > 0
        else __adguardhome_latest_release.json.tag_name
      }}

- name: Set AdGuardHome download URL fact.
  ansible.builtin.set_fact:
    __adguardhome_download_url: >-
      https://github.com/AdguardTeam/AdGuardHome/releases/download/{{
        __adguardhome_version }}/AdGuardHome_linux_{{ adguardhome_arch }}.tar.gz

- name: Check installed AdGuardHome version.
  ansible.builtin.command:
    cmd: "{{ adguardhome_bin_file }} --version"
  register: __adguardhome_installed
  changed_when: false
  failed_when: false

- name: "Download AdGuardHome {{ __adguardhome_version }}."
  ansible.builtin.unarchive:
    src: "{{ __adguardhome_download_url }}"
    dest: "{{ adguardhome_bin_dir }}"
    remote_src: true
    include:
      - "./AdGuardHome/AdGuardHome"
    extra_opts:
      - "--strip-components=2"
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_group }}"
    mode: "0755"
  when: >-
    __adguardhome_installed.rc != 0
    or __adguardhome_version not in __adguardhome_installed.stdout

- name: Allow binary to bind to privileged ports as non-root user.
  community.general.capabilities:
    path: "{{ adguardhome_bin_file }}"
    capability: "{{ __cap }}"
    state: present
  loop:
    - "cap_net_bind_service+eip"
    - "cap_net_raw+eip"
  loop_control:
    loop_var: __cap
  when: adguardhome_user != "root"

- name: Remove capabilities from binary when running as root.
  community.general.capabilities:
    path: "{{ adguardhome_bin_file }}"
    capability: "{{ __cap }}"
    state: absent
  loop:
    - "cap_net_bind_service+eip"
    - "cap_net_raw+eip"
  loop_control:
    loop_var: __cap
  when: adguardhome_user == "root"

- name: Copy systemd service.
  ansible.builtin.template:
    src: adguardhome.service.j2
    dest: "/etc/systemd/system/{{ adguardhome_service_name }}.service"
    mode: "0644"
  notify: adguardhome_reload_systemd

- name: Ensure handlers are notified before enabling new service.
  ansible.builtin.meta: flush_handlers

- name: Ensure service is enabled at boot.
  ansible.builtin.service:
    name: "{{ adguardhome_service_name }}"
    enabled: "{{ adguardhome_service_enabled }}"
