---
lxc_vmid: 100
lxc_hostname: "caddy"
lxc_appname: "Caddy"

lxc_memory: 512

lxc_network:
  - id: net0
    name: eth0
    ip4: 192.168.1.120
    netmask4: 24
    gw4: 192.168.1.1

lxc_tags:
  - "webserver"

caddy_base_domain: "{{ vault_caddy_base_domain }}"
caddy_email: "{{ vault_caddy_email }}"

caddy_ntfy_domain: "ntfy.{{caddy_base_domain }}"
caddy_ntfy_addr: 192.168.1.121:8081
