---
- name: Clone git reporitory locally.
  ansible.builtin.git:
    repo: "{{ portfolio_repo }}"
    dest: "{{ portfolio_root }}"
    version: "{{ portfolio_repo_branch }}"

- name: Deploy portfolio Docker Compose stack.
  ansible.builtin.include_role:
    name: roles/docker_compose
  vars:
    docker_compose_root: "{{ portfolio_root }}"
    docker_compose_templates:
      - src: compose.yml.j2
        dest: compose.yml
