---
nfs_mounts:
  # TODO: Use domain name instead of fixed IP
  - src: "{{ nfs_server_address }}:/tank/photo"
    path: "/mnt/photo"
    fstype: "nfs"
    opts: "rw,sync,hard,noatime,nofail,_netdev,rsize=131072,wsize=131072"
