---
nfs_mounts:
  # TODO: Use domain name instead of fixed IP
  - src: "10.0.0.3:/tank/photo"
    path: "/mnt/photo"
    fstype: "nfs"
    opts: "rw,sync,hard,noatime,nofail,_netdev,rsize=131072,wsize=131072"
