---
proxmox_host: vega
proxmox_kvm:
  vmid: 1030
  name: "{{ inventory_hostname }}"
  template_vmid: "{{ kvm_default_template_vmid }}"
  template_name: "{{ kvm_default_template_name }}"
  ciuser: "{{ kvm_default_user }}"
  cipassword: "{{ kvm_default_password }}"
  sshkeys: "{{ kvm_default_pubkey }}"
  cores: 2
  memory: 2048
  ipconfig:
    ipconfig0: >-
      ip={{
        (interfaces.lan.ip4.address ~ '/' ~ interfaces.lan.ip4.prefix) |
        ansible.utils.ipaddr('host/prefix')
      }},gw={{
        network.gw4
      }}
  scsi:
    scsi0:
      storage: "{{ kvm_default_disk_storage }}"
      size: 10 # TODO: Increase disk size
  rng0: "/dev/urandom"
  nameservers: "{{ dns.servers | join(',') }}"
  searchdomains: "{{ dns.search_domains | join(',') }}"
  onboot: true
  startup: "order=30"
  tags:
    - "docker"
