---
system_groups_host:
  - name: "docker"
    # Ensure shared photo group exists
  - name: "photo"
    gid: 2001
  # Group for non-root docker containers
  - name: "apps"
    gid: 1010

system_users_host:
  # Ensure root user can access photo
  - name: "root"
    groups:
      - "photo"
    append: true

  # Ensure admin user can access docker and photo
  - name: "lorenzo"
    groups:
      - "docker"
      - "photo"
    append: true

  # Shared photo user
  - name: "photo"
    uid: 2001
    comment: "Owns shared photo directories"
    group: "photo"
    password_lock: true
    system: true
    create_home: false
    shell: /usr/sbin/nologin

  # User for non-root docker containers
  - name: "apps"
    uid: 1010
    comment: "Manage non-root Docker containers"
    group: "apps"
    password_lock: true
    system: true
    create_home: false
    shell: /usr/sbin/nologin
