- name: Create a test LXC.
  hosts: node
  become: true

  tasks:
    - name: Delete LXC
      include_role:
        name: roles/create-lxc
        tasks_from: delete.yml
      vars:
        lxc_vmid: 100
        proxmox_node: pve-test
        proxmox_api_host: 192.168.1.51
        proxmox_api_user: root@pam
        proxmox_api_password: password
