- name: Create a test LXC.
  hosts: node
  become: true
  vars_files:
    - "{{ inventory_dir }}/host_vars/lxc.yml"
  tasks:
    - name: Delete LXC
      include_role:
        name: roles/create-lxc
        tasks_from: delete.yml
