- name: Create a test LXC.
  hosts: node
  become: true
  vars_files:
    - "{{ inventory_dir }}/host_vars/lxc.yml"
  roles:
    - role: roles/create-lxc

- name: Provision test LXC.
  hosts: lxc
  become: true
  roles:
    - role: roles/setup-base-lxc
