---
roles:
  - name: geerlingguy.docker
  - name: lae.proxmox

collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.docker
  - name: community.general
  - name: community.proxmox
  - name: grafana.grafana
