---
roles:
  - name: geerlingguy.docker

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: community.proxmox
  - name: grafana.grafana
  - name: maxhoesel.caddy
