---
dependencies: []

galaxy_info:
  author: Lorenzo Calisti
  description: Install and configure prometheus-pve-exporter in a Python venv on Proxmox VE.
  license: "license (MIT)"
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - prometheus
    - proxmox
    - monitoring
