---
lxc_vmid: 101
lxc_hostname: "ntfy"
lxc_appname: "NTFY"
lxc_cores: 1
lxc_memory: 512
lxc_disk_size: 4
lxc_network:
  - id: net0
    name: eth0
    ip4: 192.168.1.121
    netmask4: 24
    gw4: 192.168.1.1
lxc_tags:
  - "notification"

ntfy_system_user: ntfy
ntfy_system_group: ntfy

ntfy_dirs_cache: /var/cache/ntfy
ntfy_dirs_data: /var/lib/ntfy
ntfy_dirs_log: /var/log/ntfy
