---
lxc_vmid: 101
lxc_hostname: "ntfy"
lxc_appname: "NTFY"
lxc_cores: 1
lxc_memory: 512
lxc_disk_size: 4
lxc_network:
  - id: net0
    name: eth0
    ip4: 192.168.1.121
    netmask4: 24
    gw4: 192.168.1.1
lxc_tags:
  - "notification"

ntfy_config:
  base-url: "https://{{ proxy_ntfy_domain }}"
  behind-proxy: true
  listen-http: ":{{ proxy_ntfy_port }}"
  cache-file: "/var/cache/ntfy/cache.db"
  attachment-cache-dir: "/var/cache/ntfy/attachments"
  auth-file: "/var/lib/ntfy/user.db"
  auth-default-access: "deny-all"
  auth-users:
    - "{{ ntfy_admin_user }}:{{ ntfy_admin_password }}:admin"
