---
motd_content: |

  --------------------------------------------------------------------------
                      This system is managed by Ansible
  --------------------------------------------------------------------------

  NOTE: System and application configuration for this host is managed by
  automated systems. To ensure that any changes you make here are not lost,
  please contact your system administrators.

  FQDN:     {{ ansible_facts.fqdn }}
  Distro:   {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }} {{ ansible_facts.distribution_release }}
  Virtual:  {{ 'YES (' ~ ansible_facts.virtualization_type ~ ')' if ansible_facts.virtualization_role == 'guest' else 'NO' }}
  CPUs:     {{ ansible_facts.processor_vcpus }}
  RAM:      {{ (ansible_facts.memtotal_mb / 1000) | round(1) }} GB
  Timezone: {{ ansible_facts.date_time.tz }}({{ ansible_date_time.tz_offset }})

  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
