---
all:
  hosts:
    node:
      ansible_host: 192.168.1.51
    caddy:
      ansible_host: 192.168.1.120
    ntfy:
      ansible_host: 192.168.1.121
    docker:
      ansible_host: 192.168.1.122
  vars:
    ansible_user: root
