---
all:
  children:
    pvenodes:
      hosts:
        node:
          ansible_host: 192.168.1.51
          ansible_user: root
    lxcs:
      hosts:
        caddy:
          ansible_host: 192.168.1.120
        ntfy:
          ansible_host: 192.168.1.121
        docker:
          ansible_host: 192.168.1.122
        influxdb:
          ansible_host: 192.168.1.123
      vars:
        ansible_user: root

    proxy:
      hosts:
        caddy:
        docker:
        ntfy:
        influxdb:

    shared_data_clients:
      hosts:
        docker:

    notification_clients:
      hosts:
        ntfy:
