---
all:
  children:
    hypervisor:
      hosts:
        vega:
    guest:
      children:
        lxc:
    lxc:
      hosts:
        mercury-dns:
        mars-proxy:
        earth-docker:
        ntfy:
        influxdb:
        grafana:
