---
- name: Install Caddy from package manager.
  ansible.builtin.include_tasks: install-package.yml
  when: caddy_plugins | length == 0

- name: Install Caddy with xcaddy.
  ansible.builtin.include_tasks: install-xcaddy.yml
  when: caddy_plugins | length > 0

- name: Enable Caddy service at boot.
  ansible.builtin.service:
    name: "{{ caddy_service_name }}"
    enabled: true
