---
adguardhome_config:
  schema_version: 34
  http:
    address: "0.0.0.0:3000"
  users: "{{ vault_adguard_users }}"
  language: "en"
  dns:
    upstream_dns:
      - "https://dns.quad9.net/dns-query"
      - "https://protective.joindns4.eu/dns-query"
    bootstrap_dns:
      - "9.9.9.9"
      - "149.112.112.112"
      - "1.1.1.1"
    fallback_dns:
      - "9.9.9.9"
      - "149.112.112.112"
      - "86.54.11.1"
  dhcp:
    enabled: true
    interface_name: "{{ interfaces.lan.device }}"
    local_domain_name: >-
      {{
        dns.search_domains |
        ansible.builtin.first |
        ansible.builtin.mandatory
      }}
    dhcpv4:
      gateway_ip: "{{ network.gw4 }}"
      subnet_mask: "{{ network.ip4 | ansible.utils.ipaddr('netmask') }}"
      range_start: "{{ network.ip4 | ansible.utils.nthhost(150) }}"
      range_end: "{{ network.ip4 | ansible.utils.nthhost(250) }}"
      lease_duration: 86400
  filtering:
    rewrites:
      - answer: "{{ network.ip4 | ansible.utils.nthhost(20) }}"
        domain: "{{ network.domain }}"
        enabled: true
      - answer: "{{ network.ip4 | ansible.utils.nthhost(20) }}"
        domain: "*.{{ network.domain }}"
        enabled: true
