---
adguardhome_config:
  schema_version: 34
  http:
    address: "0.0.0.0:3000"
  users: "{{ vault_adguard_users }}"
  language: "en"
  dns:
    upstream_mode: "parallel"
    upstream_dns:
      # Use unfiltered DNS servers for unrestricted access
      - "https://dns10.quad9.net/dns-query"
      - "https://unfiltered.joindns4.eu/dns-query"
      - "https://doh.dns.sb/dns-query"
    bootstrap_dns:
      # For bootstrapping we use the IPv4 address of the same servers
      - "9.9.9.10"
      - "86.54.11.100"
      - "185.222.222.222"
      - "1.1.1.1"
      - "8.8.8.8"
    fallback_dns:
      # In case the European DNS servers are not available
      # fallback to Google and Cloudflare
      - "https://dns.google/dns-query"
      - "https://cloudflare-dns.com/dns-query"
  dhcp:
    enabled: true
    interface_name: "{{ interfaces.lan.device }}"
    local_domain_name: >-
      {{
        dns.search_domains |
        ansible.builtin.first |
        ansible.builtin.mandatory
      }}
    dhcpv4:
      gateway_ip: "{{ network.gw4 }}"
      subnet_mask: "{{ network.ip4 | ansible.utils.ipaddr('netmask') }}"
      range_start: "{{ network.ip4 | ansible.utils.nthhost(150) }}"
      range_end: "{{ network.ip4 | ansible.utils.nthhost(250) }}"
      lease_duration: 86400
  filtering:
    rewrites:
      - answer: "{{ network.ip4 | ansible.utils.nthhost(20) }}"
        domain: "{{ network.domain }}"
        enabled: true
      - answer: "{{ network.ip4 | ansible.utils.nthhost(20) }}"
        domain: "*.{{ network.domain }}"
        enabled: true
