---
- name: Setup ddns-updater docker stack.
  hosts: docker
  become: true

  roles:
    - role: roles/docker-compose-deploy
      vars:
        compose_project_name: "ddns"
        compose_pull_images: true
