---
caddy_sites:
  - name: "adguard"
    content: |
        https://adguard.{{ network.domain }} {
          import logging "adguard.log"
          import encode
          import private

          reverse_proxy "{{ interfaces.lan.ip4.address }}:3000"
        }
