---
#########################################
# Play that creates the LXC on the node.
#########################################
- name: Create caddy LXC.
  hosts: node
  become: true
  vars_files:
    - "{{ inventory_dir }}/host_vars/caddy.yml"
    - "{{ inventory_dir }}/group_vars/lxcs/vars.yml"
    - "{{ inventory_dir }}/group_vars/lxcs/vault.yml"
  roles:
    - role: roles/create-lxc

#############################
# Play that sets up the host.
#############################
- name: Provision caddy LXC.
  hosts: caddy
  become: true

  handlers:
    - name: restart caddy service
      ansible.builtin.service:
        name: caddy
        state: restarted

  roles:
    - role: roles/setup-base-lxc

  tasks:
    - name: Install dependencies.
      ansible.builtin.apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - gpg
        update_cache: true
        cache_valid_time: 3600

    - name: Install caddy.
      block:
        - name: Download caddy's gpg key.
          ansible.builtin.get_url:
            url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
            dest: /usr/share/keyrings/caddy-stable-archive-keyring.key
            mode: "0644"

        - name: Dearmor gpg key.
          ansible.builtin.command: sudo gpg --yes --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg /usr/share/keyrings/caddy-stable-archive-keyring.key
          args:
            creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

        - name: Add caddy's repository to apt sources.
          ansible.builtin.get_url:
            url: "https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt"
            dest: /etc/apt/sources.list.d/caddy-stable.list
            mode: "0644"

        - name: Insall caddy from the official repository.
          ansible.builtin.apt:
            name:
              - caddy
            update_cache: true
            cache_valid_time: 3600
            state: present

        - name: Enable caddy service on boot.
          ansible.builtin.service:
            name: caddy
            enabled: true
            state: started

    - name: Copy Caddyfile.
      ansible.builtin.copy:
        src: Caddyfile
        dest: /etc/caddy/Caddyfile
      notify: restart caddy service
