---
- name: Update APT cache.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution == "Debian"

- name: Perform dist-upgrade on the system.
  ansible.builtin.apt:
    upgrade: "dist"
  when:
    - ansible_distribution == "Debian"
    - lxc_dist_upgrade is true

# TODO: Perform dist-upgrade for systems other than Debian.
- name: Fail dist-upgrade if we are not on debian.
  ansible.builtin.fail:
    msg: "Cannot perform dist-upgrade on the system (we are not on Debian)."
  when: ansible_distribution != "Debian"

- name: Install core dependencies.
  ansible.builtin.package:
    name: "{{ lxc_core_deps }}"
    state: present
