---
- name: "Set system locale to '{{ lxc_locale }}'."
  block:
    - name: Generate system locale.
      community.general.locale_gen:
        name: "{{ lxc_locale }}"
        state: present

    - name: Get current locale configuration.
      ansible.builtin.command: localectl status
      register: locale_status
      changed_when: false

    - name: Parse 'LANG' from current locale configuration.
      ansible.builtin.set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

    - name: "Set locale to '{{ lxc_locale }}'."
      ansible.builtin.command: "localectl set-locale LANG={{ lxc_locale }}"
      when: locale_lang != lxc_locale
      changed_when: locale_lang != lxc_locale

- name: "Set system timezone to '{{ lxc_timezone }}'."
  community.general.timezone:
    name: "{{ lxc_timezone }}"
