---
proxmox_node: "{{ inventory_hostname }}"
proxmox_api_user: "{{ vault_proxmox_api_user }}"
proxmox_api_token_id: "{{ vault_proxmox_api_token_id }}"
proxmox_api_token_secret: "{{ vault_proxmox_api_token_secret }}"

pve_group: # No cluster.
pve_fqdn: "{{ inventory_hostname }}.{{ network.domain | ansible.builtin.mandatory }}"
pve_groups:
  - name: admin
    comment: System Administrators
pve_users:
  # User password is the same as the Linux password.
  - name: lcalisti@pam
    email: l.calisti96@gmail.com
    firstname: Lorenzo
    lastname: Calisti
    groups:
      - admin
pve_acls:
  - path: /
    roles:
      - Administrator
    groups:
      - admin

pve_pcie_passthrough_enabled: true
pve_iommu_passthrough_mode: true

pve_storages:
  - name: local
    type: dir
    path: /var/lib/vz
    content:
      - iso
      - vztmpl
      - snippets
      - backup
  - name: local-lvm
    type: lvmthin
    content:
      - images
      - rootdir
    vgname: pve
    thinpool: data
