---
- name: Load OS-specific vars.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - main.yml
      paths:
        - "vars"

- name: Ensure locale packages are present.
  ansible.builtin.package:
    name: "{{ system_locale_packages }}"
    state: present

- name: Generate locale.
  when: ansible_facts['os_family'] == 'Debian'
  community.general.locale_gen:
    name: "{{ system_locale_lang }}"

- name: Set locale.
  ansible.builtin.lineinfile:
    path: "{{ system_locale_file }}"
    regexp: "{{ __lang.regexp }}"
    line: "{{ __lang.line }}"
    create: true
    owner: root
    group: root
    mode: "0644"
  loop:
    - regexp: '^LANG='
      line: "LANG={{ system_locale_lang }}"
    - regexp: '^LC_ALL='
      line: "LC_ALL={{ system_locale_lang }}"
  loop_control:
    loop_var: __lang
    label: "{{ __lang.line }}"

- name: Set timezone.
  community.general.timezone:
    name: "{{ system_locale_timezone }}"
