---
all:
  children:
    # --- Structural groups (real machines, and VMs) ---
    # Physical Proxmox hosts
    hypervisor:
      hosts:
        vega:

    # All VMs and containers
    guest:
      children:
        lxc:
        kvm:
    lxc:
      hosts:
        mercury-dns:
        mars-proxy:
    kvm:
      hosts:

    # --- Functional groups ---
    # Used by playbooks as targets across inventories.
    dns:
      hosts:
        mercury-dns:
    proxy:
      hosts:
        mars-proxy:
    docker:
      hosts:
