---
dependencies: []

galaxy_info:
  role_name: adguardhome
  author: Lorenzo Calisti
  description: Install and configure AdGuard Home on Linux.
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - dns
    - adguard
    - adguardhome
