#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/docker-compose-deploy
compose_base_dir: "/compose"
compose_src_dir: "{{ playbook_dir }}"
compose_files_dir: "{{ [compose_src_dir, 'files'] | ansible.builtin.path_join }}"
compose_templates_dir: "{{ [compose_src_dir, 'templates'] | ansible.builtin.path_join }}"

compose_exclude_files:
  - ".gitignore"
  - ".gitkeep"

compose_pull_images: false
compose_prune_images: true
compose_prune_dangling_images: true

compose_owner: "root"
compose_group: "root"
compose_mode: "0755"
