---
caddy_global_options: |
    email "djonline96@gmail.com"
    acme_dns infomaniak "{{ vault_infomaniak_token }}"

caddy_snippets:
  - "files/caddy/snippets/encode.caddy.j2"
  - "files/caddy/snippets/logging.caddy.j2"
  - "files/caddy/snippets/private.caddy.j2"

caddy_sites:
  - name: "basesite"
    content: |
        https://{{ network.domain }} {
          import logging "basesite.log"
          import encode
          import private

          respond 200 {
            body "Hi from {{ network.domain }}!!!"
            close
          }
        }

caddy_plugins:
  - "github.com/caddy-dns/infomaniak"
