---
caddy_xcaddy_cleanup: false
caddy_trust_local_ca: true
caddy_global_options: |
    debug

    email "djonline96@gmail.com"
    local_certs

caddy_snippets:
  - "files/caddy/snippets/encode.caddy.j2"
  - "files/caddy/snippets/logging.caddy.j2"
  - "files/caddy/snippets/private.caddy.j2"

caddy_sites:
  - name: "basesite"
    content: |
        https://{{ network.domain }} {
          import logging "basesite.log"
          import encode
          import private

          route {
            teapot
          }
        }

caddy_plugins:
  - "github.com/hairyhenderson/caddy-teapot-module"
