---
dns:
  search_domains:
    - "home.arpa"
  servers:
    - "{{ network.ip4 | ansible.utils.nthhost(20) | ansible.builtin.mandatory }}"
    - "{{ network.ip4 | ansible.utils.nthhost(1) | ansible.builtin.mandatory }}"
