---
motd_content: |

  --------------------------------------------------------------------------
                      This system is managed by Ansible
  --------------------------------------------------------------------------
  - - - - - - - - - - - - - - - Staging - - - - - - - - - - - - - - - - - -

  FQDN:     {{ ansible_facts['fqdn'] | default('') }}
  Distro:   {{
      ansible_facts['distribution'] | default('')
    }} {{
      ansible_facts['distribution_version'] | default('')
    }} {{
      ansible_facts['distribution_release'] | default('')
    }}
  Virtual:  {{
      'YES (' ~ ansible_facts['virtualization_type'] ~ ')'
      if ansible_facts.get('virtualization_role') == 'guest'
      else 'NO'
    }}
  CPUs:     {{ ansible_facts['processor_vcpus'] | default('') }}
  RAM:      {{ ((ansible_facts['memtotal_mb'] | default(0)) / 1000) | round(1) }} GB
  Timezone: {{
      ansible_facts['date_time'].tz | default('')
    }} ({{
      ansible_facts['date_time'].tz_offset | default('')
    }})
  IPv4:     {{ ansible_facts['all_ipv4_addresses'] | default([]) | join(', ') }}
  IPv6:     {{ ansible_facts['all_ipv6_addresses'] | default([]) | join(', ') }}

  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
