---
system_groups: [] # noqa: var-naming[no-role-prefix]
system_users: [] # noqa: var-naming[no-role-prefix]

# Default shell for new users.
system_users_default_shell: "/bin/bash"

# Includedir command for sudoers file.
system_users_sudo_includedir: "@includedir /etc/sudoers.d"
# Command used to validate the sudoers file.
system_users_sudo_validate_cmd: "/usr/sbin/visudo -cf %s"
system_users_sudo_mode: "0440"

system_users_packages:
  - sudo
