---
lxc_vmid: 100
lxc_hostname: "test"
lxc_password: "{{ vault_lxc_password }}"
lxc_appname: "Test"
lxc_pubkey: "{{ vault_lxc_pubkey }}"
lxc_network:
  - id: net0
    name: eth0
    ip4: 192.168.1.120
    netmask4: 24
    gw4: 192.168.1.1
lxc_mounts:
  - id: mp0
    bind: /mnt/binds
    mount: /shared
