---
caddy_sites:
  - name: "jellyfin"
    content: |
        https://media.{{ network.domain }} {
          import logging "jellyfin.log"
          import encode
          import private

          reverse_proxy "{{ interfaces.lan.ip4.address }}:8096"
        }
