---
# yaml-language-server: $schema=none
prometheus_file_sd:
  node:
    - targets: ["{{ ansible_host }}:{{ node_exporter_port }}"]
      labels:
        hostname: "{{ inventory_hostname }}"
  blackbox:
    - targets: ["https://{{ jellyfin_domain }}"]
      labels:
        module: http_2xx
