---
system_groups:
  # Ensure render group exist for iGPU passthrough
  - name: render
    gid: 104
  # Ensure shared media group exist
  - name: media
    gid: 2000

system_users:
  # Ensure jellyfin user can access shared media
  - name: jellyfin
    groups:
      - media
    append: true
