---
system_groups_host:
  # Ensure render group exist for iGPU passthrough
  - name: render
    gid: 104
  # Ensure shared media group exist
  - name: media
    gid: 2000

system_users_host:
  # Ensure jellyfin user can access shared media
  - name: jellyfin
    groups:
      - media
    append: true

  # Ensure admin user can access shared media
  - name: "lorenzo"
    groups:
      - "media"
    append: true
