---
proxy_base_domain: "{{ vault_proxy_base_domain }}"

proxy_ntfy_domain: "ntfy.{{ proxy_base_domain }}"
proxy_ntfy_address: 192.168.1.121
proxy_ntfy_port: 8081

proxy_homepage_domain: "homepage.{{ proxy_base_domain }}"
proxy_homepage_address: 192.168.1.122
proxy_homepage_port: 3000
