---
- name: "Create LXC '{{ lxc_hostname }}' ({{ lxc_vmid }})."
  community.general.proxmox:
    # Specify the API info for the proxmox node
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"

    # Specify main info about the LXC
    vmid: "{{ lxc_vmid }}"
    hostname: "{{ lxc_hostname }}"
    password: "{{ lxc_password }}"
    ostemplate: "{{ lxc_template_storage }}:vztmpl/{{ lxc_template }}"

    # Create privileged/unprivileged LXC
    unprivileged: "{{ lxc_unprivileged }}"

    # Set hardware info
    cores: "{{ lxc_cores }}"
    memory: "{{ lxc_memory }}"
    swap: "{{ lxc_swap }}"
    features: "{{ lxc_features | default(omit) }}"

    # Set main disk
    disk_volume:
      storage: "{{ lxc_disk_storage }}"
      size: "{{ lxc_disk_size }}"

    # Set additional mount points.
    # TODO: Add more mount types other than bind mounts.
    mounts: >-
      { {%- for item in lxc_mounts -%}
        "{{ item.id }}": "{{ item.bind }},mp={{ item.mount }}",
      {%- endfor -%} }

    # Set network interfaces
    netif: >-
      { {%- for item in lxc_network -%}
        "{{ item.id }}":"name={{ item.name }},bridge={{ item.bridge | default('vmbr0') }},{% if (item.ip4 is defined) %}ip={{ item.ip4 }}{% endif %}{% if (item.netmask4 is defined) %}/{{ item.netmask4 }},{% else %},{% endif %}{% if (item.gw4 is defined) %}gw={{ item.gw4 }},{% endif %}{% if (item.ip6 is defined) %}ip6={{ item.ip6 }}{% endif %}{% if (item.netmask6 is defined) %}/{{ item.netmask6 }},{% else %},{% endif %}{% if (item.gw6 is defined) %}gw6={{ item.gw6 }},{% endif %}{% if (item.firewall is defined and item.firewall) %}firewall=1,{% endif %}{% if (item.vlan_tag is defined) %}tag={{ item.vlan_tag }}{% endif %}",
      {%- endfor -%} }

    # Set boot options
    onboot: "{{ lxc_onboot }}"
    # TODO: Change lxc_startup option to lxc_boot_order
    startup: "{{ lxc_startup if (lxc_startup is defined and lxc_startup | length > 0) else omit }}"

    # Set DNS nameserver
    nameserver: "{{ lxc_nameserver if (lxc_nameserver is defined and lxc_nameserver | length > 0) else omit }}"

    # Set SSH pubkey for remote access
    # TODO: Add SSH key of the proxmox node for future management
    pubkey: "{{ lookup('file', lxc_pubkey) if (lxc_pubkey is defined and lxc_pubkey | length > 0) else omit }}"

    # Set the description
    # TODO: Include all IPs in the description.
    description: |
      <div>
        <h2 align="center" style="font-size: 24px; margin: 20px 0">
            {{ lxc_appname }} LXC
        </h2>
        <p style="margin: 16px 0">
            <strong>Note: </strong>This Proxmox LXC container is managed by Ansible.
            Please contact your system administrators to ensure that any changes you
            make here are not lost.
        </p>
        <ul>
          <li><strong>Hostname: </strong>{{ lxc_hostname }}</li>
          <li><strong>CPUs: </strong>{{ lxc_cores }}</li>
          <li><strong>RAM: </strong>{{ lxc_memory }}MB</li>
          <li><strong>Storage: </strong>{{ lxc_disk_size }}GB</li>
        </ul>
      </div>

    # Set tags
    tags: "{{ lxc_tags + ['ansible'] }}"

    # If the LXC already exsists no need to update it
    # TODO: Bug when using `update` parameter with `ostemplate`, they are mutually exclusive.
    # update: false

    # Ensure the LXC is created
    state: present
