---
- name: Include status task.
  ansible.builtin.include_tasks: status.yml

- name: "Stop LXC '{{ lxc_hostname }}' ({{ lxc_vmid }})."
  community.general.proxmox:
    # Specify the API info for the proxmox node
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"

    # Specify main info about the LXC
    vmid: "{{ lxc_vmid }}"

    # Ensure the LXC is deleted
    state: stopped
  when: lxc_is_running

- name: "Delete LXC '{{ lxc_hostname }}' ({{ lxc_vmid }})."
  community.general.proxmox:
    # Specify the API info for the proxmox node
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"

    # Specify main info about the LXC
    vmid: "{{ lxc_vmid }}"

    # Ensure the LXC is deleted
    state: absent
