---
- name: Get status of LXC.
  block:
    - name: "Get status of LXC '{{ lxc_vmid }}'."
      community.proxmox.proxmox_vm_info:
        node: "{{ proxmox_node }}"
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        vmid: "{{ lxc_vmid }}"
      register: _proxmox_lxc_status
      changed_when: false

    - name: "Set fact if LXC '{{ lxc_vmid }}' exists."
      ansible.builtin.set_fact:
        lxc_exists: "{{ _proxmox_lxc_status.proxmox_vms | length > 0 | bool }}"

    - name: "Set fact if LXC '{{ lxc_vmid }}' is running."
      ansible.builtin.set_fact:
        lxc_is_running: "{{ _proxmox_lxc_status.proxmox_vms[0].status == 'running' }}"
      when: lxc_exists

- name: "Ensure LXC '{{ lxc_hostname }}' ({{ lxc_vmid }}) is stopped."
  community.proxmox.proxmox:
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ lxc_vmid }}"
    state: stopped
  when:
    - lxc_exists
    - lxc_is_running

- name: "Ensure LXC '{{ lxc_hostname }}' ({{ lxc_vmid }}) is deleted."
  community.proxmox.proxmox:
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ lxc_vmid }}"
    state: absent
  when: lxc_exists
