---
- name: Check required variables.
  ansible.builtin.assert:
    that:
      - item in vars
      - vars[item] is not in [None, '']
    fail_msg: "Required variable {{ item }} is not defined."
    quiet: true
  loop:
    - proxmox_node
    - proxmox_api_host
    - proxmox_api_user
    - lxc_vmid
    - lxc_hostname
    - lxc_password
    - lxc_appname

- name: Check for password or token authentication.
  block:
    - name: Register password setup.
      ansible.builtin.set_fact:
        proxmox_is_password_setup: >-
          {{ proxmox_api_password is defined
          and proxmox_api_password is string
          and proxmox_api_password | length > 0 }}
    - name: Register token setup.
      ansible.builtin.set_fact:
        proxmox_is_token_setup: >-
          {{ proxmox_api_token_id is defined
          and proxmox_api_token_id is string
          and proxmox_api_token_id | length > 0
          and proxmox_api_token_secret is defined
          and proxmox_api_token_secret is string
          and proxmox_api_token_secret | length > 0 }}
    - name: Check conflict between password and token setup.
      ansible.builtin.assert:
        that: "(not proxmox_is_password_setup and proxmox_is_token_setup) or (proxmox_is_password_setup and not proxmox_is_token_setup)"
        fail_msg: "proxmox_api_password or proxmox_api_token_id and proxmox_api_token_secret must be defined, but not both."
        quiet: true

- name: Ensure pip is present.
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Ensure proxmox dependencies are present.
  ansible.builtin.pip:
    name:
      - proxmoxer>=2.0
      - requests
    break_system_packages: true
