---
- name: "Get status of LXC '{{ lxc_vmid }}'."
  community.general.proxmox_vm_info:
    # Specify the API info for the proxmox node
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"

    # vmid of the LXC to check
    vmid: "{{ lxc_vmid }}"
  register: lxc_status
  changed_when: false

- name: Set facts if LXC is running.
  ansible.builtin.set_fact:
    lxc_is_running: "{{ lxc_status.proxmox_vms[0].status == 'running'}}"
