---
caddy_sites:
  - name: "influxdb"
    content: |
        https://influxdb.{{ network.domain }} {
          import logging "influxdb.log"
          import encode
          import private

          reverse_proxy "{{ interfaces.lan.ip4.address }}:8086"
        }
