---
proxmox_host: vega
proxmox_lxc:
  vmid: 1021
  hostname: "{{ inventory_hostname }}"
  password: "{{ lxc_default_password }}"
  pubkey: "{{ lxc_default_pubkey }}"
  template:
    name: "{{ lxc_default_template }}"
    timeout: "{{ lxc_default_template_timeout }}"
  disk_volume:
    storage: "local-lvm"
    size: 6
  cores: 1
  memory: 512
  netif:
    net0: >-
      name={{ interfaces.lan.device }},ip={{
        (interfaces.lan.ip4.address ~ '/' ~ interfaces.lan.ip4.prefix) |
        ansible.utils.ipaddr('host/prefix')
      }},gw={{
        network.gw4
      }},bridge=vmbr0
  nameserver: "{{ dns.servers | join(',') }}"
  searchdomain: "{{ dns.search_domains | join(',') }}"
  onboot: true
  startup: "order=20"
  features:
    - "keyctl=1"
    - "nesting=1"
  tags:
    - "webserver"
    - "proxy"
