---
#########################################
# Play that creates the LXC on the node.
#########################################
- name: Create grafana LXC.
  hosts: node
  become: true
  vars_files:
    - "{{ inventory_dir }}/host_vars/grafana/vars.yml"
    - "{{ inventory_dir }}/host_vars/grafana/vault.yml"
    - "{{ inventory_dir }}/group_vars/lxcs/vars.yml"
    - "{{ inventory_dir }}/group_vars/lxcs/vault.yml"
  roles:
    - role: roles/create-lxc

#############################
# Play that sets up the host.
#############################
- name: Provision grafana LXC.
  hosts: grafana
  become: true

  roles:
    - role: roles/setup-base-lxc
    - role: grafana.grafana.grafana
      vars:
        grafana_ini:
          security:
            admin_user: "{{ grafana_admin_user }}"
            admin_password: "{{ grafana_admin_password }}"
            allow_embedding: "{{ grafana_allow_embedding }}"
          server:
            http_port: "{{ proxy_grafana_port }}"
            root_path: "https://{{ proxy_grafana_domain }}"
          users:
            allow_sign_up: "{{ grafana_allow_sign_up }}"
            allow_org_create: "{{ grafana_allow_org_create }}"
            auto_assign_org_role: "{{ grafana_auto_assign_org_role }}"
          metrics:
            enabled: "{{ grafana_enable_metrics }}"
        grafana_dashboards_dir: "dashboards"
