---
lxc_vmid: 103
lxc_hostname: "influxdb"
lxc_appname: "InfluxDB"
lxc_cores: 2
lxc_memory: 2048
lxc_disk_size: 8
lxc_network:
  - id: net0
    name: eth0
    ip4: 192.168.1.123
    netmask4: 24
    gw4: 192.168.1.1
lxc_tags:
  - "database"

influxdb_host: http://localhost:8086
influxdb_primary_org: "{{ vault_influxdb_primary_org }}"
influxdb_primary_bucket: "{{ vault_influxdb_primary_bucket }}"
influxdb_primary_username: "{{ vault_influxdb_primary_username }}"
influxdb_primary_password: "{{ vault_influxdb_primary_password }}"
influxdb_admin_token: "{{ vault_influxdb_admin_token }}"
