---
all:
  children:
    hypervisor:
      hosts:
        vega:
    guest:
      children:
        lxc:
        kvm:
    lxc:
      hosts:
        mercury-dns:
        mars-proxy:
        ntfy:
        influxdb:
        grafana:
    kvm:
      hosts:
        earth-docker:
