---
system_users:
  # Ansible management user
  - name: ansible
    comment: "Ansible management user"
    authorized_keys:
      - "{{ controller_ssh_pubkey }}"
    sudo_options:
      - "ALL=(ALL) NOPASSWD: ALL"
  # Personal admin user
  - name: lorenzo
    comment: "Lorenzo Calisti"
    authorized_keys:
      - "{{ controller_ssh_pubkey }}"
    sudo_options:
      - "ALL=(ALL) ALL"
