---
system_groups:
  - name: "media"
    gid: 2000
  - name: "photo"
    gid: 2001
  - name: "backup"
    gid: 2010

system_users:
  # Ansible management user
  - name: ansible
    comment: "Ansible management user"
    password_lock: true
    generate_ssh_key: true
    authorized_keys:
      - "{{ controller_ssh_pubkey }}"
    sudo_options:
      - "ALL=(ALL) NOPASSWD: ALL"

  # Personal admin user
  - name: lorenzo
    comment: "Lorenzo Calisti"
    password: "{{ vault_admin_password }}"
    generate_ssh_key: true
    authorized_keys:
      - "{{ controller_ssh_pubkey }}"
    sudo_options:
      - "ALL=(ALL) ALL"

  # Shared media user
  - name: "media"
    uid: 2000
    comment: "Owns shared media directories"
    group: "media"
    password_lock: true
    system: true
    create_home: false
    shell: /usr/sbin/nologin

  # Shared photo user
  - name: "photo"
    uid: 2001
    comment: "Owns shared photo directories"
    group: "photo"
    password_lock: true
    system: true
    create_home: false
    shell: /usr/sbin/nologin

  # Backup user
  - name: "backup"
    uid: 2010
    comment: "Owns shared backup directories"
    group: "backup"
    password_lock: true
    system: true
    create_home: false
    shell: /usr/sbin/nologin
