---
- name: adguardhome_reload_systemd # noqa: name[casing]
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: adguardhome_restart_systemd_resolved # noqa: name[casing]
  ansible.builtin.service:
    name: "systemd-resolved"
    state: "restarted"
