---
- name: reload systemd daemon # noqa: name[casing]
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: restart systemd-resolved # noqa: name[casing]
  ansible.builtin.service:
    name: "systemd-resolved"
    state: "restarted"
