---
- name: Pull latest images in the compose stack.
  community.docker.docker_compose_v2_pull:
    project_src: "{{ compose_target_dir }}"
  when: "compose_pull_images | bool"

- name: Deploy the compose stack.
  community.docker.docker_compose_v2:
    project_src: "{{ compose_target_dir }}"
    state: present

- name: Prune unused and dangling Docker images.
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: "{{ compose_prune_dangling_images }}"
  when: "compose_prune_images | bool"
