---
system_groups:
  - name: "shared_data"
    gid: 2000

system_users:
  # Shared data user
  - name: "shared_data"
    uid: 2000
    comment: "Owns shared data directories (media, photos, backups)."
    group: "shared_data"
    password_lock: true
    system: true
    create_home: false
    shell: /usr/sbin/nologin

  # root user
  - name: "root"
    groups:
      - "shared_data"
    append: true
