---
immich_root: /srv/stacks/immich
immich_port: 2283
immich_domain: "photo.{{ network.domain }}"
immich_db_password: "{{ vault_immich_db_password }}"

immich_metrics_enabled: true
immich_metrics_port_server: 8081
immich_metrics_port_microservices: 8082
