---
# yaml-language-server: $schema=none
prometheus_file_sd:
  node:
    - targets: ["{{ interfaces.lan.ip4.address }}:{{ node_exporter_port }}"]
      labels:
        hostname: "{{ inventory_hostname }}"
  docker:
    - targets: ["{{ interfaces.lan.ip4.address }}:8080"]
      labels:
        hostname: "{{ inventory_hostname }}"
  immich:
    - targets:
        - "{{ interfaces.lan.ip4.address }}:{{ immich_metrics_port_server }}"
        - "{{ interfaces.lan.ip4.address }}:{{ immich_metrics_port_microservices }}"
      labels:
        hostname: "{{ inventory_hostname }}"
  blackbox:
    - targets:
        - "https://{{ ddns_domain }}"
        - "https://{{ vaultwarden_domain }}"
        - "https://{{ portfolio_domain }}"
        - "https://{{ immich_domain }}"
      labels:
        module: http_2xx
