---
vaultwarden_domain: "vaultwarden.{{ network.domain }}"
vaultwarden_port: 8001

vaultwarden_root: /srv/stacks/vaultwarden
vaultwarden_remote_dir: "/test-data/vaultwarden_backup"
vaultwarden_rclone_config:
  type: "smb"
  host: "{{ smb_server_address }}"
  user: "shared_data"
  pass: "{{ vault_vaultwarden_smb_pass }}"
vaultwarden_config:
  domain: "https://{{ vaultwarden_domain }}"
  signups_allowed: true
  invitations_allowed: false
  email_change_allowed: false
  password_hints_allowed: true
  show_password_hint: true
  admin_token: "{{ vault_vaultwarden_admin_token }}"
