---
caddy_requirements:
  - nss-tools

caddy_packages:
  - caddy

caddy_rpm_repo: >-
  https://download.copr.fedorainfracloud.org/results/@caddy/caddy/{{
    'fedora' if ansible_facts['distribution'] | lower == 'fedora' else 'epel'
  }}-$releasever-$basearch/
caddy_rpm_key: "https://download.copr.fedorainfracloud.org/results/@caddy/caddy/pubkey.gpg"
