---
caddy_requirements:
  - python3-requests

caddy_packages:
  - caddy

caddy_service: caddy

caddy_rpm_repo: >-
  https://download.copr.fedorainfracloud.org/results/@caddy/caddy/{{
    'fedora' if ansible_distribution | lower == 'fedora' else 'epel'
  }}-$releasever-$basearch/"
caddy_rpm_key: "https://download.copr.fedorainfracloud.org/results/@caddy/caddy/pubkey.gpg"
