- name: Create a test LXC.
  hosts: node
  become: true

  tasks:
    - name: Delete LXC
      include_role:
        name: roles/create-lxc
        tasks_from: delete.yml
      vars:
        lxc_vmid: "{{ item }}"
        lxc_hostname: "UNKNOWN"
      loop:
        - 100
