---
- name: Configure Linux systems.
  hosts: all:!hypervisor
  become: true
  gather_facts: false
  tags: linux
  roles:
    - role: system_locale
      when: ansible_facts['distribution'] != 'Alpine'
      tags: locale
    - role: system_update
      tags: update
    - role: system_users
      tags: users
    - role: ssh
      tags: ssh
    - role: motd
      tags: motd
