---
- name: Gather facts for all physical hosts.
  hosts: all:!guest
  gather_facts: false
  become: true
  tags: always
  tasks:
    - name: Gather facts for physical hosts that do not have disable_fact_gathering=true.
      when: not (disable_fact_gathering | default(false) | bool)
      ansible.builtin.setup:

- name: Import Proxmox configuration playbook.
  ansible.builtin.import_playbook: proxmox.yml

- name: Gather facts for all virtual hosts.
  hosts: guest
  gather_facts: false
  become: true
  tags: always
  tasks:
    - name: Gather facts for virtual hosts that do not have disable_fact_gathering=true.
      when: not (disable_fact_gathering | default(false) | bool)
      ansible.builtin.setup:

- name: Import Linux configuration playbook.
  ansible.builtin.import_playbook: linux.yml

- name: Import Networking services playbook.
  ansible.builtin.import_playbook: networking.yml

- name: Import Monitoring services playbook.
  ansible.builtin.import_playbook: monitoring.yml

- name: Import other services playbook.
  ansible.builtin.import_playbook: services.yml
