---
- name: Configure Prometheus.
  hosts: prometheus
  become: true
  gather_facts: false
  roles:
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_scrape_configs: >-
          {{
            groups['all'] |
            map('ansible.builtin.extract', hostvars) |
            selectattr('prometheus_scrape_configs', 'defined') |
            map(attribute='prometheus_scrape_configs') |
            list |
            flatten
          }}
      tags: prometheus

- name: Configure node_exporter on all hosts.
  hosts: exporter
  become: true
  gather_facts: false
  roles:
    - role: prometheus.prometheus.node_exporter
      tags: node_exporter

- name: Configure pve_exporter on Proxmox VE hosts.
  hosts: hypervisor
  become: true
  gather_facts: false
  roles:
    - role: pve_exporter
      tags: pve_exporter

- name: Configure cAdvisor exporter on Docker hosts.
  hosts: docker
  become: true
  gather_facts: false
  roles:
    - role: prometheus.prometheus.cadvisor
      tags: cadvisor

- name: Configure Grafana.
  hosts: grafana
  become: true
  gather_facts: false
  roles:
    - role: grafana.grafana.grafana
      tags: grafana

- name: Configure InfluxDB.
  hosts: influxdb
  become: true
  gather_facts: false
  roles:
    - role: influxdb2
      tags: influxdb

- name: Configure NTFY.
  hosts: ntfy
  become: true
  gather_facts: false
  roles:
    - role: ntfy
      tags: ntfy
