---
- name: Configure Prometheus.
  hosts: prometheus
  become: true
  gather_facts: false
  roles:
    - role: prometheus.prometheus.prometheus
      vars:
        # Conbine all targets defined in the distributed `prometheus_file_sd` variable.
        # Each host can define a targets for jobs using this dictionary where the key is
        # the job name and the value is a `file_sd_config`.
        # Note: The jobs must be also declared in `prometheus_scrape_configs`.
        prometheus_targets: >-
          {{
            {} |
            combine(
              groups['exporter'] |
                map('ansible.builtin.extract', hostvars) |
                selectattr('prometheus_file_sd', 'defined') |
                map(attribute='prometheus_file_sd'),
              list_merge='append'
            )
          }}
      tags: prometheus

- name: Configure node_exporter on all enabled hosts.
  hosts: exporter
  become: true
  gather_facts: false
  roles:
    - role: prometheus.prometheus.node_exporter
      tags: node_exporter

- name: Configure cAdvisor exporter on Docker hosts.
  hosts: docker
  become: true
  gather_facts: false
  roles:
    - role: prometheus.prometheus.cadvisor
      tags: cadvisor

- name: Configure Grafana.
  hosts: grafana
  become: true
  gather_facts: false
  roles:
    - role: grafana.grafana.grafana
      tags: grafana

- name: Configure InfluxDB.
  hosts: influxdb
  become: true
  gather_facts: false
  roles:
    - role: influxdb2
      tags: influxdb

- name: Configure NTFY.
  hosts: ntfy
  become: true
  gather_facts: false
  roles:
    - role: ntfy
      tags: ntfy
