---
- name: Configure Docker hosts.
  hosts: docker
  become: true
  gather_facts: false
  roles:
    - role: geerlingguy.docker
      tags: docker

- name: Configure Docker services.
  hosts: docker
  become: true
  gather_facts: false
  roles:
    - role: ddns
      tags: ddns
    - role: vaultwarden
      tags: vaultwarden
    - role: portfolio
      tags: portfolio
    - role: immich
      tags: immich
    - role: homepage
      tags: homepage
