---
- name: Configure services hosted on Docker.
  hosts: docker
  become: true
  gather_facts: false
  roles:
    - role: geerlingguy.docker
      tags: docker
    - role: ddns
      tags: ddns
    - role: vaultwarden
      tags: vaultwarden
    - role: portfolio
      tags: portfolio
    - role: immich
      tags: immich
