---
#########################################
# Play that creates the LXC on the node.
#########################################
- name: Create docker LXC.
  hosts: node
  become: true
  vars_files:
    - "{{ inventory_dir }}/host_vars/docker/proxmox.yml"
  roles:
    - role: roles/create-lxc

#############################
# Play that sets up the host.
#############################
- name: Provision docker LXC.
  hosts: docker
  become: true

  roles:
    - role: roles/setup-base-lxc

  tasks:
    - name: Install docker.
      block:
        - name: Add docker's repository to apt.
          ansible.builtin.deb822_repository:
            name: Docker
            architectures: amd64
            components: stable
            signed_by: https://download.docker.com/linux/debian/gpg
            suites: bookworm
            types: deb
            uris: https://download.docker.com/linux/debian

        - name: Install docker from the official repository.
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            update_cache: true
            state: present

        - name: Enable docker service on boot.
          ansible.builtin.service:
            name: docker
            enabled: true
            state: started
