---
#########################################
# Play that creates the LXC on the node.
#########################################
- name: Create docker LXC.
  hosts: node
  become: true
  vars_files:
    - "{{ inventory_dir }}/host_vars/docker/vars.yml"
    - "{{ inventory_dir }}/host_vars/docker/vault.yml"
    - "{{ inventory_dir }}/group_vars/lxcs/vars.yml"
    - "{{ inventory_dir }}/group_vars/lxcs/vault.yml"
  roles:
    - role: roles/create-lxc

#############################
# Play that sets up the host.
#############################
- name: Provision docker LXC.
  hosts: docker
  become: true

  roles:
    - role: roles/setup-base-lxc
    - role: geerlingguy.docker
