---
# yaml-language-server: $schema=none
blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      follow_redirects: true
      tls_config:
        insecure_skip_verify: true
  dns_public:
    prober: dns
    timeout: 5s
    dns:
      query_name: "google.com"
      query_type: A
      valid_rcodes:
        - NOERROR
  dns_internal:
    prober: dns
    timeout: 5s
    dns:
      query_name: "{{ prometheus_domain }}"
      query_type: A
      valid_rcodes:
        - NOERROR
