---
# yaml-language-server: $schema=none
prometheus_domain: "prometheus.{{ network.domain }}"
prometheus_file_sd_dir: "/etc/prometheus/file_sd"
prometheus_storage_retention: "30d"
prometheus_storage_retention_size: "2GB"

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

prometheus_external_labels:
  env: staging

prometheus_alert_rules: []

prometheus_alertmanager_config:
  - static_configs:
      - targets:
          - "localhost:9093"

prometheus_file_sd:
  node:
    - targets: ["{{ interfaces.lan.ip4.address }}:{{ node_exporter_port }}"]
      labels:
        hostname: "{{ inventory_hostname }}"
  blackbox:
    - targets:
        - "https://{{ prometheus_domain }}"
        - "https://{{ alertmanager_domain }}"
      labels:
        module: http_2xx

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:{{ prometheus_port }}"
        labels:
          hostname: "{{ inventory_hostname }}"
  - job_name: "alertmanager"
    static_configs:
      - targets:
          - "localhost:9093"
        labels:
          hostname: "{{ inventory_hostname }}"
  - job_name: "node"
    file_sd_configs:
      - files: ["{{ prometheus_file_sd_dir }}/node.yml"]
  - job_name: "pve"
    file_sd_configs:
      - files: ["{{ prometheus_file_sd_dir }}/pve.yml"]
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
  - job_name: "zfs"
    file_sd_configs:
      - files: ["{{ prometheus_file_sd_dir }}/zfs.yml"]
  - job_name: "smartctl"
    file_sd_configs:
      - files: ["{{ prometheus_file_sd_dir }}/smartctl.yml"]
  - job_name: "docker"
    file_sd_configs:
      - files: ["{{ prometheus_file_sd_dir }}/docker.yml"]
  - job_name: "caddy"
    file_sd_configs:
      - files: ["{{ prometheus_file_sd_dir }}/caddy.yml"]
  - job_name: "blackbox"
    metrics_path: /probe
    file_sd_configs:
      - files: ["{{ prometheus_file_sd_dir }}/blackbox.yml"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: "localhost:9115"
