---
name: Vault Check

on:
  pull_request:
  push:

# Cancel previous runs when a new commit is started
concurrency:
  group: ${{ github.workflow }} - ${{ github.ref }}
  cancel-in-progress: true

jobs:
  encrypted-vaults:
    name: Ensure vault files are encrypted.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest version of the project.
        uses: actions/checkout@v6

      - name: Ensure all vault files are encrypted.
        run: ./tools/vault_check.sh
