---
caddy_sites:
  - name: "ntfy"
    content: |
        https://{{ ntfy_domain }} {
          import logging "ntfy.log"
          import encode
          import private

          reverse_proxy "{{ interfaces.lan.ip4.address }}:{{ ntfy_port }}"
        }
